name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  sudo scripts/prerequisites.sh
    - name: cpu cores
      run: cat /proc/cpuinfo | grep "cpu cores" | uniq
    - name: raspberrypi4
      run: ./mcf -p  1 -b 1 raspberrypi4
    - name: make webos-image
      run: make webos-image
   
      
      
