name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  sudo scripts/prerequisites.sh
    - name: cpu cores
      run: cat /proc/cpuinfo | grep "cpu cores" | uniq
